2017-02-13 19:00:00,593 PyNaCl is not installed, voice will NOT be supported
2017-02-13 19:00:00,594 on_message has successfully been registered as an event
2017-02-13 19:00:00,595 on_member_join has successfully been registered as an event
2017-02-13 19:00:00,596 logging in using static token
2017-02-13 19:00:01,719 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-13 19:00:01,723 sent the identify payload to create the websocket
2017-02-13 21:38:13,202 Failing the WebSocket connection: 1006 
2017-02-13 21:38:13,207 Websocket closed with 1006 (), attempting a reconnect.
2017-02-13 21:38:13,208 Got ResumeWebSocket
2017-02-13 21:38:13,663 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-13 21:38:13,667 sent the resume payload to create the websocket
2017-02-14 02:00:52,508 Failing the WebSocket connection: 1011 
2017-02-14 02:00:52,510 Websocket closed with 1006 (), attempting a reconnect.
2017-02-14 02:00:52,511 Got ResumeWebSocket
2017-02-14 02:00:53,073 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-14 02:00:53,079 sent the resume payload to create the websocket
2017-02-14 03:23:23,498 Failing the WebSocket connection: 1011 
2017-02-14 03:23:23,500 Websocket closed with 1006 (), attempting a reconnect.
2017-02-14 03:23:23,501 Got ResumeWebSocket
2017-02-14 03:23:23,895 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-14 03:23:23,898 sent the resume payload to create the websocket
2017-02-14 13:18:49,532 Websocket closed with 1001 (), attempting a reconnect.
2017-02-14 13:18:49,533 Got ResumeWebSocket
2017-02-14 13:18:49,989 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-14 13:18:49,992 sent the resume payload to create the websocket
2017-02-14 21:09:16,709 PyNaCl is not installed, voice will NOT be supported
2017-02-14 21:09:16,710 on_message has successfully been registered as an event
2017-02-14 21:09:16,710 on_member_join has successfully been registered as an event
2017-02-14 21:09:16,711 logging in using static token
2017-02-14 21:09:17,365 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-14 21:09:17,368 sent the identify payload to create the websocket
2017-02-14 21:26:43,495 PyNaCl is not installed, voice will NOT be supported
2017-02-14 21:26:43,496 on_message has successfully been registered as an event
2017-02-14 21:26:43,497 on_member_join has successfully been registered as an event
2017-02-14 21:26:43,498 logging in using static token
2017-02-14 21:26:44,060 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-14 21:26:44,064 sent the identify payload to create the websocket
2017-02-14 21:39:11,126 PyNaCl is not installed, voice will NOT be supported
2017-02-14 21:39:11,127 on_message has successfully been registered as an event
2017-02-14 21:39:11,127 on_member_join has successfully been registered as an event
2017-02-14 21:39:11,128 logging in using static token
2017-02-14 21:39:11,671 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-14 21:39:11,675 sent the identify payload to create the websocket
2017-02-15 14:48:15,323 Websocket closed with 1001 (CloudFlare WebSocket proxy restarting), attempting a reconnect.
2017-02-15 14:48:15,324 Got ResumeWebSocket
2017-02-15 14:48:15,751 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-15 14:48:15,754 sent the resume payload to create the websocket
2017-02-15 16:51:00,780 Websocket closed with 1001 (CloudFlare WebSocket proxy restarting), attempting a reconnect.
2017-02-15 16:51:00,781 Got ResumeWebSocket
2017-02-15 16:51:01,403 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-15 16:51:01,409 sent the resume payload to create the websocket
2017-02-15 19:34:25,195 Failing the WebSocket connection: 1006 
2017-02-15 19:34:25,200 Websocket closed with 1006 (), attempting a reconnect.
2017-02-15 19:34:25,201 Got ResumeWebSocket
2017-02-15 19:34:25,716 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-15 19:34:25,722 sent the resume payload to create the websocket
2017-02-15 20:21:52,370 Websocket closed with 1001 (), attempting a reconnect.
2017-02-15 20:21:52,371 Got ResumeWebSocket
2017-02-15 20:21:52,776 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-15 20:21:52,781 sent the resume payload to create the websocket
2017-02-15 20:50:45,554 Websocket closed with 1001 (), attempting a reconnect.
2017-02-15 20:50:45,555 Got ResumeWebSocket
2017-02-15 20:50:45,957 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-15 20:50:45,961 sent the resume payload to create the websocket
2017-02-15 20:56:15,998 Failing the WebSocket connection: 1011 
2017-02-15 20:56:16,000 Websocket closed with 1006 (), attempting a reconnect.
2017-02-15 20:56:16,001 Got ResumeWebSocket
2017-02-15 20:56:16,396 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-15 20:56:16,399 sent the resume payload to create the websocket
2017-02-15 21:16:54,011 Failing the WebSocket connection: 1006 
2017-02-15 21:16:54,015 Websocket closed with 1006 (), attempting a reconnect.
2017-02-15 21:16:54,016 Got ResumeWebSocket
2017-02-15 21:16:54,414 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-15 21:16:54,420 sent the resume payload to create the websocket
2017-02-15 21:18:35,531 Failing the WebSocket connection: 1011 
2017-02-15 21:18:35,533 Websocket closed with 1006 (), attempting a reconnect.
2017-02-15 21:18:35,534 Got ResumeWebSocket
2017-02-15 21:18:36,051 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-15 21:18:36,054 Task exception was never retrieved
future: <Task finished coro=<WebSocketCommonProtocol.run() done, defined at /usr/local/lib/python3.5/site-packages/websockets/protocol.py:407> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 413, in run
    msg = yield from self.read_message()
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 435, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 490, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 525, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/framing.py", line 80, in read_frame
    data = yield from reader(2)
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 670, in readexactly
    block = yield from self.read(n)
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 627, in read
    yield from self._wait_for_data('read')
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 457, in _wait_for_data
    yield from self._waiter
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 669, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
2017-02-15 21:18:36,075 sent the resume payload to create the websocket
2017-02-15 21:35:48,372 Failing the WebSocket connection: 1006 
2017-02-15 21:35:48,376 Websocket closed with 1006 (), attempting a reconnect.
2017-02-15 21:35:48,377 Got ResumeWebSocket
2017-02-15 21:35:48,991 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-15 21:35:48,994 sent the resume payload to create the websocket
2017-02-15 22:37:41,815 Failing the WebSocket connection: 1011 
2017-02-15 22:37:41,817 Websocket closed with 1006 (), attempting a reconnect.
2017-02-15 22:37:41,818 Got ResumeWebSocket
2017-02-15 22:37:42,307 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-15 22:37:42,310 sent the resume payload to create the websocket
2017-02-15 22:39:04,825 Failing the WebSocket connection: 1011 
2017-02-15 22:39:04,827 Websocket closed with 1006 (), attempting a reconnect.
2017-02-15 22:39:04,827 Got ResumeWebSocket
2017-02-15 22:39:05,220 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-15 22:39:05,223 sent the resume payload to create the websocket
2017-02-16 02:40:03,287 Websocket closed with 1001 (CloudFlare WebSocket proxy restarting), attempting a reconnect.
2017-02-16 02:40:03,288 Got ResumeWebSocket
2017-02-16 02:40:03,738 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-16 02:40:03,742 sent the resume payload to create the websocket
2017-02-16 08:40:02,379 Task exception was never retrieved
future: <Task finished coro=<WebSocketCommonProtocol.run() done, defined at /usr/local/lib/python3.5/site-packages/websockets/protocol.py:407> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 413, in run
    msg = yield from self.read_message()
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 435, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 490, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 525, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/framing.py", line 80, in read_frame
    data = yield from reader(2)
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 670, in readexactly
    block = yield from self.read(n)
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 627, in read
    yield from self._wait_for_data('read')
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 457, in _wait_for_data
    yield from self._waiter
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 669, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
2017-02-16 08:40:02,383 Task exception was never retrieved
future: <Task finished coro=<WebSocketCommonProtocol.run() done, defined at /usr/local/lib/python3.5/site-packages/websockets/protocol.py:407> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 413, in run
    msg = yield from self.read_message()
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 435, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 490, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 525, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "/usr/local/lib/python3.5/site-packages/websockets/framing.py", line 80, in read_frame
    data = yield from reader(2)
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 670, in readexactly
    block = yield from self.read(n)
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 627, in read
    yield from self._wait_for_data('read')
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 457, in _wait_for_data
    yield from self._waiter
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 669, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
2017-02-16 10:55:15,316 Message blocked: Vad vi här nere kallar klydderövar 😃 <@!95500709658636288> From: Bellsibong#5786
2017-02-16 18:34:03,099 PyNaCl is not installed, voice will NOT be supported
2017-02-16 18:34:03,100 on_message has successfully been registered as an event
2017-02-16 18:34:03,100 on_member_join has successfully been registered as an event
2017-02-16 18:34:03,101 logging in using static token
2017-02-16 18:34:03,711 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-16 18:34:03,715 sent the identify payload to create the websocket
2017-02-16 18:38:23,691 PyNaCl is not installed, voice will NOT be supported
2017-02-16 18:38:23,692 on_message has successfully been registered as an event
2017-02-16 18:38:23,693 on_member_join has successfully been registered as an event
2017-02-16 18:38:23,694 logging in using static token
2017-02-16 18:38:24,516 Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
2017-02-16 18:38:24,523 sent the identify payload to create the websocket
